name: airsim-js Test

on: [push, workflow_dispatch]

jobs:
  airsim-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: |
          export SDL_VIDEODRIVER_VALUE=offscreen
          export SDL_HINT_CUDA_DEVICE=0
          wget https://github.com/microsoft/AirSim/releases/download/v1.8.0-linux/Blocks.zip
          unzip Blocks.zip
          Blocks/LinuxNoEditor/Blocks.sh -settings=settings.json
          sleep 10
          ps aux
          sleep 10


