name: airsim-js Test

on: [push, workflow_dispatch]

jobs:
  airsim-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      # - uses: actions/schmiddim-wget-unzip@v1
      #   with:
      #     url: 'https://github.com/hpool-dev/chia-miner/releases/download/1.5.6/HPool-Miner-chia-og-v1.5.6-1-linux.zip'
      #     destination: arm-release
      # - uses: actions/schmiddim-wget-unzip@v1
      #   with:
      #     url: 'https://github.com/microsoft/AirSim/releases/download/v1.8.0-windows/Blocks.zip'
      #     destination: /airsim
      - run: |
          pwd
          ls -la /
          # ls -laR /airsim
