name: airsim-js Test

on: [push, workflow_dispatch]

jobs:
  airsim-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Download and Install AirSim - Blocks env
      - run: |
          wget https://github.com/microsoft/AirSim/releases/download/v1.8.0-linux/Blocks.zip
          ls -la /
          unzip Blocks.zip
          ls -laR Blocks
